#!/usr/bin/env python3
"""Runtime config.toml. Loopback only. Unknown keys ignored. Never secrets."""
from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any

try:
    import tomllib
except ImportError:  # pragma: no cover
    import tomli as tomllib  # type: ignore

DEFAULTS: dict[str, Any] = {
    "aide_init_policy": "allow_known_warn",
    "scan_sudo_mode": "prompt",
    "docker_stop_idle": True,
    "timer_enabled": True,
    "watch_timer": False,
    "ai_enabled": False,
    "ai_model": "grok-4.6",
    "ai_after_scan": True,
    "listen_bind": "127.0.0.1",
    "listen_port": 8787,
    "apparmor_enforce_selected": False,
    "verbose": False,
    "notify_on_alert": True,
    "skip_hunt": False,
    "skip_rootkit": False,
    "defs_auto_update": False,
    "nmap_localhost": True,
    "nmap_port_spec": "-",
    "helper_stale_check": True,
    "aide_watch_helper": True,
    "proc_inventory": True,
    "proc_hidden_check": True,
    "proc_ioc_check": True,
    "pcap_localhost": True,
    "pcap_duration_s": 8,
    "pcap_max_packets": 4000,
    "nmap_svc_probe": True,
    "ufw_digest": True,
    "web_terminal": True,
}
ENUMS = {
    "aide_init_policy": {"clean_only", "allow_known_warn", "always_prompt"},
    "scan_sudo_mode": {"prompt", "helper", "never"},
}
READONLY = frozenset({"listen_bind", "listen_port"})
# watch_timer omitted from file → None (timer script runs; Settings infers systemd)
OPTIONAL_BOOL = frozenset({"watch_timer"})


def config_path() -> Path:
    env = os.environ.get("KALIVED_CONFIG")
    if env:
        return Path(env)
    home = os.environ.get("KALIVED_OWNER_HOME") or str(Path.home())
    return Path(home) / ".config" / "kalived" / "config.toml"


def _raw() -> dict[str, Any]:
    p = config_path()
    if not p.is_file():
        return {}
    with p.open("rb") as fh:
        loaded = tomllib.load(fh) or {}
    return loaded if isinstance(loaded, dict) else {}


def validate(data: dict[str, Any]) -> dict[str, Any]:
    out = dict(DEFAULTS)
    out.update({k: data[k] for k in DEFAULTS if k in data})
    for k, allowed in ENUMS.items():
        if out[k] not in allowed:
            raise ValueError(f"{k}={out[k]!r} ikke i {sorted(allowed)}")
    bind = str(out["listen_bind"])
    if bind not in ("127.0.0.1", "::1", "localhost"):
        raise ValueError(f"listen_bind={bind!r} må være loopback")
    port = int(out["listen_port"])
    if not 1 <= port <= 65535:
        raise ValueError(f"listen_port={port}")
    spec = str(out["nmap_port_spec"]).strip() or "-"
    if spec != "-" and not all(c.isdigit() or c in "-," for c in spec):
        raise ValueError("nmap_port_spec er porter, ikke host")
    if "/" in spec or spec.lower() in ("any", "all"):
        raise ValueError("nmap_port_spec er porter, ikke mål")
    out["nmap_port_spec"] = spec
    dur = int(out["pcap_duration_s"])
    if not 1 <= dur <= 30:
        raise ValueError("pcap_duration_s 1–30")
    out["pcap_duration_s"] = dur
    mx = int(out["pcap_max_packets"])
    if not 1 <= mx <= 20000:
        raise ValueError("pcap_max_packets 1–20000")
    out["pcap_max_packets"] = mx
    for k, v in list(out.items()):
        if isinstance(DEFAULTS.get(k), bool):
            if isinstance(v, str):
                out[k] = v.strip().lower() in ("1", "true", "yes", "on")
            else:
                out[k] = bool(v)
    return out


def load() -> dict[str, Any]:
    raw = _raw()
    data = validate({k: raw[k] for k in raw if k in DEFAULTS})
    present = {k for k in OPTIONAL_BOOL if k in raw}
    data["_present"] = sorted(present)
    return data


def dump_toml(data: dict[str, Any]) -> str:
    lines = ["# generated by kalived PUT /v1/config", ""]
    for k, default in DEFAULTS.items():
        v = data.get(k, default)
        if isinstance(default, bool):
            lines.append(f"{k} = {'true' if bool(v) else 'false'}")
        elif isinstance(default, int) and not isinstance(default, bool):
            lines.append(f"{k} = {int(v)}")
        else:
            lines.append(f'{k} = "{v}"')
    return "\n".join(lines) + "\n"


def write(data: dict[str, Any]) -> Path:
    valid = validate(data)
    valid.pop("_present", None)
    path = config_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(dump_toml(valid), encoding="utf-8")
    os.chmod(tmp, 0o600)
    tmp.replace(path)
    os.chmod(path, 0o600)
    owner = os.environ.get("SUDO_USER")
    if owner and os.geteuid() == 0:
        try:
            import pwd

            pw = pwd.getpwnam(owner)
            os.chown(path, pw.pw_uid, pw.pw_gid)
        except (KeyError, PermissionError, OSError):
            pass
    return path


def patch(updates: dict[str, Any]) -> dict[str, Any]:
    cur = load()
    for k, v in updates.items():
        if k.startswith("_") or k not in DEFAULTS:
            continue
        if k in READONLY:
            raise ValueError(f"{k} er låst (loopback)")
        cur[k] = v
    write(cur)
    return load()


def watch_explicit() -> bool | None:
    raw = _raw()
    if "watch_timer" not in raw:
        return None
    v = raw["watch_timer"]
    if isinstance(v, str):
        return v.strip().lower() in ("1", "true", "yes", "on")
    return bool(v)


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("usage: kalived_config.py dump|get KEY|set KEY VAL", file=sys.stderr)
        return 2
    cmd = argv[1]
    if cmd == "dump":
        d = load()
        d.pop("_present", None)
        sys.stdout.write(dump_toml(d))
        return 0
    if cmd == "get" and len(argv) >= 3:
        d = load()
        print(d.get(argv[2], ""))
        return 0
    if cmd == "set" and len(argv) >= 4:
        key, val = argv[2], argv[3]
        if val.lower() in ("true", "1", "yes", "on"):
            parsed: Any = True
        elif val.lower() in ("false", "0", "no", "off"):
            parsed = False
        elif val.isdigit():
            parsed = int(val)
        else:
            parsed = val
        patch({key: parsed})
        print("ok", key, parsed)
        return 0
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
