#!/usr/bin/env python3
"""kalived local API — loopback only, bearer token. stdlib."""
from __future__ import annotations

import json
import os
import secrets
import subprocess
import sys
import tomllib
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(os.environ.get("KALIVED_ROOT", Path(__file__).resolve().parent.parent))
OWNER = os.environ.get("KALIVED_OWNER") or os.environ.get("SUDO_USER") or os.environ.get("USER") or "void"
HOME = Path(os.environ.get("KALIVED_OWNER_HOME") or f"/home/{OWNER}")
DATA = Path(os.environ.get("KALIVED_DATA", ROOT))
CONFIG_PATH = Path(os.environ.get("KALIVED_CONFIG", HOME / ".config/kalived/config.toml"))
TOKEN_PATH = Path(os.environ.get("KALIVED_API_TOKEN", HOME / ".config/kalived/api.token"))
SCAN = ROOT / "scripts" / "kalived-scan.sh"
UPDATE_DEFS = ROOT / "scripts" / "update-threat-defs.sh"
PLAYBOOKS = ROOT / "playbooks"

DEFAULTS = {
    "aide_init_policy": "allow_known_warn",
    "scan_sudo_mode": "prompt",
    "docker_stop_idle": True,
    "timer_enabled": True,
    "ai_enabled": False,
    "ai_model": "grok-4.6",
    "listen_bind": "127.0.0.1",
    "listen_port": 8787,
    "apparmor_enforce_selected": False,
    "verbose": False,
    "notify_on_alert": True,
    "skip_hunt": False,
    "skip_rootkit": False,
    "defs_auto_update": False,
}
ENUMS = {
    "aide_init_policy": {"clean_only", "allow_known_warn", "always_prompt"},
    "scan_sudo_mode": {"prompt", "helper", "never"},
}
PLAYBOOK_ALLOW = {
    "journald-persistent": "journald-persistent.sh",
    "auditd-mini": "auditd-mini.sh",
    "ufw-logging-medium": "ufw-logging-medium.sh",
    "aide-init": "aide-init.sh",
    "install-kalived-helper": "install-kalived-helper.sh",
    "install-scan-timer": "install-scan-timer.sh",
    "docker-hygiene": "docker-hygiene.sh",
    "rkhunter-setup": "rkhunter-setup.sh",
    "disable-vendor-rk-cron": "disable-vendor-rk-cron.sh",
    "install-config": "install-config.sh",
    "update-threat-defs": None,  # special
}
PLAYBOOK_ARGS = {
    "docker-hygiene": {"--prune", "--no-stop", "--stop"},
}


def load_config() -> dict:
    data = dict(DEFAULTS)
    if CONFIG_PATH.is_file():
        with CONFIG_PATH.open("rb") as f:
            loaded = tomllib.load(f) or {}
        if isinstance(loaded, dict):
            for k, v in loaded.items():
                if k in DEFAULTS:
                    data[k] = v
    bind = str(data["listen_bind"])
    if bind not in ("127.0.0.1", "::1", "localhost"):
        raise SystemExit(f"listen_bind={bind} not loopback — refuse")
    port = int(data["listen_port"])
    if not 1 <= port <= 65535:
        raise SystemExit("bad listen_port")
    for k, allowed in ENUMS.items():
        if data[k] not in allowed:
            raise SystemExit(f"bad {k}={data[k]}")
    return data


def ensure_token() -> str:
    TOKEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    if TOKEN_PATH.is_file():
        tok = TOKEN_PATH.read_text(encoding="utf-8").strip()
    else:
        tok = secrets.token_hex(32)
        TOKEN_PATH.write_text(tok + "\n", encoding="utf-8")
    os.chmod(TOKEN_PATH, 0o600)
    if os.geteuid() == 0 and OWNER:
        try:
            import pwd

            pw = pwd.getpwnam(OWNER)
            os.chown(TOKEN_PATH, pw.pw_uid, pw.pw_gid)
        except KeyError:
            pass
    return tok


def dump_toml(data: dict) -> str:
    lines = ["# generated by kalived API PUT /v1/config", ""]
    for k, default in DEFAULTS.items():
        v = data.get(k, default)
        if isinstance(v, bool):
            lines.append(f"{k} = {'true' if v else 'false'}")
        elif isinstance(v, int) and not isinstance(v, bool):
            lines.append(f"{k} = {v}")
        else:
            lines.append(f'{k} = "{v}"')
    return "\n".join(lines) + "\n"


def latest_snapshot() -> Path | None:
    best = None
    status = DATA / "logs" / "status"
    if not status.is_dir():
        return None
    for d in status.iterdir():
        if not d.is_dir():
            continue
        meta, verd = d / "meta.txt", d / "verdict.json"
        if not verd.is_file():
            continue
        if meta.is_file() and "kalived_scan=1" not in meta.read_text(encoding="utf-8", errors="replace"):
            continue
        if best is None or d.name > best.name:
            best = d
    return best


def list_snapshots() -> list[dict]:
    out = []
    status = DATA / "logs" / "status"
    if not status.is_dir():
        return out
    for d in sorted(status.iterdir(), key=lambda p: p.name, reverse=True):
        verd = d / "verdict.json"
        if not verd.is_file():
            continue
        try:
            doc = json.loads(verd.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        out.append(
            {
                "stamp": d.name,
                "verdict": doc.get("verdict"),
                "exit_code": doc.get("exit_code"),
                "path": str(d),
            }
        )
    return out[:50]


TOKEN = ""


class Handler(BaseHTTPRequestHandler):
    server_version = "kalived-api/1"

    def log_message(self, fmt, *args):
        sys.stderr.write("%s - %s\n" % (self.address_string(), fmt % args))

    def _send(self, code: int, obj, extra_headers=None):
        raw = json.dumps(obj, ensure_ascii=False, indent=2).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(raw)))
        self.send_header("X-Content-Type-Options", "nosniff")
        if extra_headers:
            for k, v in extra_headers.items():
                self.send_header(k, v)
        self.end_headers()
        self.wfile.write(raw)

    def _auth(self) -> bool:
        p = urlparse(self.path).path.rstrip("/") or "/"
        if p in ("/v1/health", "/", "/openapi.yaml", "/favicon.ico"):
            return True
        h = self.headers.get("Authorization", "")
        tok = ""
        if h.startswith("Bearer "):
            tok = h[7:].strip()
        tok = tok or self.headers.get("X-Kalived-Token", "").strip()
        if not tok or not secrets.compare_digest(tok, TOKEN):
            self._send(401, {"error": "unauthorized"})
            return False
        return True

    def _body(self) -> dict:
        n = int(self.headers.get("Content-Length") or 0)
        if n <= 0:
            return {}
        if n > 1_000_000:
            return {}
        raw = self.rfile.read(n)
        try:
            return json.loads(raw.decode("utf-8"))
        except json.JSONDecodeError:
            return {}

    def do_GET(self):
        u = urlparse(self.path)
        path = u.path.rstrip("/") or "/"
        if not self._auth():
            return
        if path == "/favicon.ico":
            self.send_response(204)
            self.end_headers()
            return
        if path == "/":
            return self._send(
                200,
                {
                    "service": "kalived-api",
                    "docs": "not FastAPI — no /docs UI. See /openapi.yaml and docs/SURFACE.md",
                    "auth": "Authorization: Bearer $(cat ~/.config/kalived/api.token)",
                    "health": "/v1/health",
                    "routes": [
                        "GET /v1/health",
                        "GET /v1/config",
                        "PUT /v1/config",
                        "GET /v1/verdict/latest",
                        "GET /v1/snapshots",
                        "GET /v1/snapshots/{stamp}",
                        "GET /v1/findings",
                        "GET /v1/defs/feeds",
                        "POST /v1/defs/update",
                        "POST /v1/scan",
                        "GET /v1/playbooks",
                        "POST /v1/playbooks/{name}",
                        "POST /v1/ai/advise",
                    ],
                    "mutating": "POST scan/playbooks/defs require this process running as root",
                },
            )
        if path == "/openapi.yaml":
            spec = ROOT / "api" / "openapi.yaml"
            raw = spec.read_bytes() if spec.is_file() else b"missing\n"
            self.send_response(200)
            self.send_header("Content-Type", "application/yaml")
            self.send_header("Content-Length", str(len(raw)))
            self.end_headers()
            self.wfile.write(raw)
            return
        if path == "/v1/health":
            return self._send(200, {"ok": True, "root": os.geteuid() == 0})
        if path == "/v1/config":
            return self._send(200, {"path": str(CONFIG_PATH), "config": load_config()})
        if path == "/v1/verdict/latest":
            snap = latest_snapshot()
            if not snap:
                return self._send(404, {"error": "no snapshot"})
            doc = json.loads((snap / "verdict.json").read_text(encoding="utf-8"))
            return self._send(200, doc)
        if path == "/v1/snapshots":
            return self._send(200, {"snapshots": list_snapshots()})
        if path.startswith("/v1/snapshots/"):
            stamp = path.split("/")[-1]
            snap = DATA / "logs" / "status" / stamp
            verd = snap / "verdict.json"
            if not verd.is_file():
                return self._send(404, {"error": "not found"})
            doc = json.loads(verd.read_text(encoding="utf-8"))
            md = (snap / "VERDICT.md").read_text(encoding="utf-8", errors="replace") if (snap / "VERDICT.md").is_file() else ""
            return self._send(200, {"verdict": doc, "verdict_md": md, "path": str(snap)})
        if path == "/v1/findings":
            snap = latest_snapshot()
            if not snap:
                return self._send(200, {"findings": []})
            doc = json.loads((snap / "verdict.json").read_text(encoding="utf-8"))
            return self._send(200, {"findings": doc.get("findings") or []})
        if path == "/v1/defs/feeds":
            feeds = []
            d = ROOT / "defs" / "feeds.d"
            if d.is_dir():
                for f in sorted(d.iterdir()):
                    feeds.append({"name": f.name, "text": f.read_text(encoding="utf-8", errors="replace")[:4000]})
            return self._send(200, {"feeds": feeds, "version": (ROOT / "defs" / "VERSION").read_text(encoding="utf-8").strip() if (ROOT / "defs" / "VERSION").is_file() else "?"})
        if path == "/v1/playbooks":
            return self._send(200, {"playbooks": sorted(PLAYBOOK_ALLOW)})
        return self._send(404, {"error": "not found"})

    def do_PUT(self):
        u = urlparse(self.path)
        path = u.path.rstrip("/")
        if not self._auth():
            return
        if path != "/v1/config":
            return self._send(404, {"error": "not found"})
        body = self._body()
        if not isinstance(body, dict):
            return self._send(400, {"error": "json object required"})
        cur = load_config()
        for k, v in body.items():
            if k not in DEFAULTS:
                continue
            cur[k] = v
        try:
            bind = str(cur["listen_bind"])
            if bind not in ("127.0.0.1", "::1", "localhost"):
                return self._send(400, {"error": "listen_bind must be loopback"})
            for k, allowed in ENUMS.items():
                if cur[k] not in allowed:
                    return self._send(400, {"error": f"bad {k}"})
        except Exception as e:
            return self._send(400, {"error": str(e)})
        CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
        CONFIG_PATH.write_text(dump_toml(cur), encoding="utf-8")
        os.chmod(CONFIG_PATH, 0o600)
        return self._send(200, {"ok": True, "config": load_config()})

    def do_POST(self):
        u = urlparse(self.path)
        path = u.path.rstrip("/")
        if not self._auth():
            return
        if path == "/v1/scan":
            return self._post_scan()
        if path == "/v1/defs/update":
            return self._post_defs()
        if path.startswith("/v1/playbooks/"):
            name = path.split("/")[-1]
            return self._post_playbook(name)
        if path == "/v1/ai/advise":
            return self._send(501, {"error": "AI advise not implemented", "ai_enabled": load_config().get("ai_enabled")})
        return self._send(404, {"error": "not found"})

    def _need_root(self) -> bool:
        if os.geteuid() == 0:
            return True
        self._send(
            403,
            {
                "error": "mutating endpoint requires API started as root",
                "hint": "sudo ./scripts/kalived-api.sh",
            },
        )
        return False

    def _post_scan(self):
        if not self._need_root():
            return
        body = self._body()
        cmd = ["bash", str(SCAN), "--quiet"]
        if body.get("skip_hunt") or load_config().get("skip_hunt"):
            cmd.append("--skip-hunt")
        env = os.environ.copy()
        env["KALIVED_DATA"] = str(DATA)
        env["KALIVED_OWNER"] = OWNER
        env["NO_COLOR"] = "1"
        try:
            p = subprocess.run(cmd, cwd=str(ROOT), env=env, capture_output=True, text=True, timeout=900)
        except subprocess.TimeoutExpired:
            return self._send(504, {"error": "scan timeout"})
        verd = None
        snap = latest_snapshot()
        if snap and (snap / "verdict.json").is_file():
            verd = json.loads((snap / "verdict.json").read_text(encoding="utf-8"))
        return self._send(
            200,
            {
                "exit_code": p.returncode,
                "verdict": verd,
                "stderr_tail": (p.stderr or "")[-4000:],
            },
        )

    def _post_defs(self):
        if not self._need_root():
            return
        try:
            p = subprocess.run(
                ["bash", str(UPDATE_DEFS)],
                cwd=str(ROOT),
                capture_output=True,
                text=True,
                timeout=180,
            )
        except subprocess.TimeoutExpired:
            return self._send(504, {"error": "defs update timeout"})
        return self._send(200, {"exit_code": p.returncode, "log": (p.stdout or "")[-8000:]})

    def _post_playbook(self, name: str):
        if name not in PLAYBOOK_ALLOW:
            return self._send(404, {"error": "unknown playbook", "allow": sorted(PLAYBOOK_ALLOW)})
        body = self._body()
        if body.get("confirm") is not True:
            return self._send(400, {"error": "confirm:true required"})
        if name == "update-threat-defs":
            return self._post_defs()
        if not self._need_root():
            return
        script = PLAYBOOKS / PLAYBOOK_ALLOW[name]
        args = []
        for a in body.get("args") or []:
            if not isinstance(a, str) or a not in PLAYBOOK_ARGS.get(name, set()):
                return self._send(400, {"error": f"arg not allowed: {a}"})
            args.append(a)
        try:
            p = subprocess.run(
                ["bash", str(script), *args],
                cwd=str(ROOT),
                capture_output=True,
                text=True,
                timeout=600,
            )
        except subprocess.TimeoutExpired:
            return self._send(504, {"error": "playbook timeout"})
        return self._send(200, {"exit_code": p.returncode, "log": ((p.stdout or "") + (p.stderr or ""))[-8000:]})


def main():
    global TOKEN
    cfg = load_config()
    bind = str(cfg["listen_bind"])
    if bind == "localhost":
        bind = "127.0.0.1"
    if bind not in ("127.0.0.1", "::1"):
        print("refuse non-loopback bind", file=sys.stderr)
        sys.exit(3)
    TOKEN = ensure_token()
    port = int(cfg["listen_port"])
    httpd = ThreadingHTTPServer((bind, port), Handler)
    print(f"kalived-api {bind}:{port}  token={TOKEN_PATH}", file=sys.stderr)
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
